### PR TITLE
Add BLAS and LAPACK packages to sysroot [OC-310]

### PR DESCRIPTION
**Pull request by peddie**
This is required for the sparse householder QR changes in

https://github.com/swift-nav/orion-engine/pull/7126
https://github.com/swift-nav/rules_swiftnav/pull/109
https://github.com/swift-nav/albatross/pull/453
https://github.com/swift-nav/cmake/pull/167

### CODE REVIEW

**Comment by peddie** [comment]
How do I test this?

**Review by jungleraptor — APPROVED** [review]

**Comment by jungleraptor** [comment]
@peddie after you merge if you push a tag that matches `bullseye-sysroot*` it should build and publish the new sysroots to the releases page.

And just FYI but there's an x86_64 sysroot and an aarch64 sysroot.

**Comment by peddie** [comment]
Thanks -- any tag I like?  `bullseye-sysroot-blas-lapack`?

**Comment by silverjam** [comment]
> Thanks -- any tag I like?  `bullseye-sysroot-blas-lapack`?

Should probably follow this pattern 

image

**Comment by peddie** [comment]
@silverjam thanks.

**Pull request merged**
